services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myusername
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
